// 语言切换：所有显示文本存放在 translations，默认英文，localStorage 记住偏好
const translations = {
	'en': {
		title: 'Tang & Song Poems',
		searchPlaceholder: 'Search poems or authors... (try "moon" or author:"Li Bai")',
		searchBtn: 'Search',
		filterSummary: 'Filter',
		filterFieldAuthor: 'Author',
		filterFieldDynasty: 'Dynasty',
		filterFieldTitle: 'Title',
		filterApply: 'Apply',
		filterClear: 'Clear',
		filterValuePlaceholder: '-- Choose a value --',
		dailyPoemTitle: 'Poem of the Day',
		dailyPoetTitle: 'Poet of the Day',
		randomBtn: 'Random Poem',
		resultsHeading: 'Search Results',
		resultsCount: '{count} result(s) found',
		noResults: 'No results found. Try another query.',
		randomHeading: 'Random Poem',
		backLink: 'Back to Home',
		footer: '© 2026 · Tang & Song Poems'
	},
	'zh': {
		title: '唐诗宋词',
		searchPlaceholder: '搜索诗词或作者…（试试 "明月" 或 author:"李白"）',
		searchBtn: '搜索',
		filterSummary: '筛选',
		filterFieldAuthor: '作者',
		filterFieldDynasty: '朝代',
		filterFieldTitle: '标题',
		filterApply: '应用',
		filterClear: '清除',
		filterValuePlaceholder: '-- 请选择 --',
		dailyPoemTitle: '每日诗词',
		dailyPoetTitle: '每日诗人',
		randomBtn: '随机跳转',
		resultsHeading: '搜索结果',
		resultsCount: '共找到 {count} 条结果',
		noResults: '未找到结果，请尝试其他关键词。',
		randomHeading: '随机诗词',
		backLink: '返回主页',
		footer: '© 2026 · 唐诗宋词'
	}
};
